from . import pos_payment_method_inherit
from . import product_product_inherit
from . import pos_order_inherit
from . import pos_product_categories_inherit
from . import pos_product_details
from . import pos_product_pricelist_inherit
from . import pos_account_tax_inherit
from . import pos_company_inherit
from . import company_bc
from . import pos_time_intervals
from . import pos_coupon_program_inherit
from . import pos_res_config_settings
from . import pos_restaurant_table_inherit